// This file was autogenerated by X/lib/google-closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../../iev/localStorage.js', ['iev.LocalStorage'], []);
goog.addDependency('../../../../../iev/main.js', ['iev.embryoiewer'], ['iev.LocalStorage', 'iev.specimenview']);
goog.addDependency('../../../../../iev/specimenview.js', ['iev.specimenview'], ['X.interactor2D', 'X.renderer2D']);
