var iev=iev||{};iev.embryo=function(){};iev.embryo.prototype.dcc_get=function(a,b){var c=new XMLHttpRequest;c.open("GET",a,!0);c.onreadystatechange=function(){4===c.readyState&&(200===c.status?b(JSON.parse(c.responseText)):console.error("Unable to retrieve data from "+a))};c.send(null)};iev.embryo.prototype.getVolumesByColonyId=function(a,b){this.dcc_get("rest/volumes"+(void 0===a?"":"?colony_id="+a),function(c){new iev.embryoviewer(c,"viewer","colony ID",a,b)})};
iev.embryo.prototype.getVolumesByGeneSymbol=function(a,b){this.dcc_get("rest/volumes"+(void 0===a?"":"?gene_symbol="+a),function(c){new iev.embryoviewer(c,"viewer","gene symbol",a,b)})};iev.embryo.prototype.getVolumesByMgi=function(a,b){console.log("gettigng by mgi");console.log(a);this.dcc_get("rest/volumes"+(void 0===a?"":"?mgi="+a),function(c){new iev.embryoviewer(c,"viewer","mgi",a,b)})};iev.LocalStorage=function(a){this.idbSupported=!0;this.db=null;this.id=Math.random();if(!1 in window)this.idbSupported=!1,console.log("indexedDB not supported. Loading volumes from server");else{var b=indexedDB.open("ievTest",2);b.onupgradeneeded=function(a){console.log("Upgrading iev indexedDB");a=a.target.result;a.objectStoreNames.contains("volumes")&&a.deleteObjectStore("volumes");a.createObjectStore("volumes")};b.onsuccess=function(b){console.log("idxdb Success!");this.db=b.target.result;this.db.transaction(["volumes"],
"readwrite").objectStore("volumes");console.log("1st id:",this.id);a()}.bind(this);b.onerror=function(b){console.log("Error initialising IndexedDB");console.dir(b);this.idbSupported=!1;a()}.bind(this)}};
iev.LocalStorage.prototype.getVolume=function(a,b,c){this.idbSupported?this._checkForKey(a,b,function(d){d.target.result?this._getfromIndexedDb(a,function(d){new Date(d.lastUpdate)<b?(console.log("newer data available on the server"),this._getFromServer(a,function(d){this._addVolume(a,b,d);c(d)}.bind(this))):c(d.filedata)}):this._getFromServer(a,function(d){this._addVolume(a,b,d);c(d)}.bind(this))}.bind(this)):this._getFromServer(a,function(d){this._addVolume(a,b,d);c(d)}.bind(this))};
iev.LocalStorage.prototype._checkForKey=function(a,b,c){this.db.transaction(["volumes"],"readonly").objectStore("volumes").get(a).onsuccess=c};iev.LocalStorage.prototype._addVolume=function(a,b,c){this.idbSupported&&(b={name:a,filedata:c,created:b},a=this.db.transaction(["volumes"],"readwrite").objectStore("volumes").add(b,a),a.onerror=function(a){console.log("Error",a.target.error.message)},a.onsuccess=function(){console.log("Woot! Did it")})};
iev.LocalStorage.prototype._getfromIndexedDb=function(a,b){this.idbSupported||b(this._getVolumeFromServer(a));var c=this.db.transaction(["volumes"],"readwrite").objectStore("volumes").get(a);c.onsuccess=function(a){if(a=a.target.result)console.log("retrieving volume from indexedDB"),b(a)};c.onerror=function(){console.log("failed to get from idxdb even though key exists");this._getVolumeFromServer(a,function(a){b(a)})}};
iev.LocalStorage.prototype._getFromServer=function(a,b){var c=new XMLHttpRequest;c.open("GET",a,!0);c.responseType="arraybuffer";c.send();console.log("getting data from server");c.onreadystatechange=function(){4===this.readyState&&b(this.response)}};
iev.LocalStorage.prototype.removeVolume=function(a){var b=this.db.transaction(["volumes"],"readwrite").objectStore("volumes").delete(a);b.onerror=function(){console.log("Error deleting corrupted image from IndexedDB storage")};b.onsuccess=function(){console.log(a+" successfully deleted from IndexedDB storage")}};iev.embryoviewer=function(a,b,c,d,e){this.data=a;this.IMAGE_SERVER="https://www.mousephenotype.org/images/emb/";this.WILDTYPE_COLONYID="baseline";this.queryId=d;this.horizontalView;this.wtView;this.mutView;this.currentModality;this.currentCentreId;this.downloadTableRowSource;this.spinner;this.currentZoom=0;this.currentOrientation="horizontal";this.currentViewHeight;this.bookmarkReady=!1;this.mgi;this.gene_symbol;this.availableViewHeight;this.bookmarkData=e;if("colony ID"===c&&"test"===this.queryId){var f=
$("#redirect_test_template").html(),f=Handlebars.compile(f);$("#"+b).append(f())}else{this.localStorage;this.centreData={};this.ortho={X:{visible:!0,linked:!0},Y:{visible:!0,linked:!0},Z:{visible:!0,linked:!0}};this.volorder=["203","204","202"];"null"!==this.bookmarkData.modality&&this.volorder.unshift(this.bookmarkData.modality);this.scales={currentBarSize:600,options:{"200&#956;m":200,"400&#956;m":400,"600&#956;m":600,"1mm":1E3,"2mm":2E3,"4mm":4E3,"6mm":6E3}};this.centreOptions={1:"BCM",3:"GMC",
4:"HAR",6:"ICS",7:"J",8:"TCP",9:"Ning",10:"RBRC",11:"UCD",12:"Wtsi"};this.spinnerOpts={lines:8,length:6,width:6,radius:8,scale:1,corners:1,color:"#ef7b0b",opacity:0.2,rotate:0,direction:1,speed:1,trail:50,fps:20,zIndex:2E9,className:"spinner",top:"50%",left:"70%",shadow:!1,hwaccel:!0,position:"absolute"};this.ICONS_DIR="images/centre_icons/";if(a.success){this.gene_symbol=this.mgi="undefined";for(f in a.centre_data){c=this.getModalityData();$("#top_bar").show();for(d=0;d<this.objSize(a.centre_data[f]);d++)e=
a.centre_data[f][d],this.buildUrl(e),e.colonyId===this.WILDTYPE_COLONYID?c[e.pid].vols.wildtype[e.volume_url]=e:(c[e.pid].vols.mutant[e.volume_url]=e,"undefined"===this.mgi&&(this.mgi=e.mgi),"undefined"===this.gene_symbol&&(this.gene_symbol=e.geneSymbol));this.centreData[f]=c}this.currentCentreId=f}else a={colonyId:this.queryId,queryType:c},f=$("#no_data_template").html(),f=Handlebars.compile(f),$("#"+b).append(f(a));this.container=b;this.views=[];this.catchXtkLoadError();this.setBreadCrumb();this.setInitialViewerHeight();
this.setActiveModalityButtons();this.loadViewers();this.attachEvents();this.beforeReady();this.setScaleSelect()}};iev.embryoviewer.prototype.scaleLabels=function(){var a=[],b;for(b in this.scales.options)a.push("<option value='"+this.scales.options[b]+"'>"+b+"</option>");return a};iev.embryoviewer.prototype.getModalityData=function(){return{203:{id:"CT E14.5/15.5",vols:{mutant:{},wildtype:{}}},204:{id:"CT E18.5",vols:{mutant:{},wildtype:{}}},202:{id:"OPT 9.5",vols:{mutant:{},wildtype:{}}}}};
iev.embryoviewer.prototype.centreSelector=function(){var a=[],b;for(b in this.centreOptions)b in this.data.centre_data&&a.push("<option  value='"+b+"'' data-class='"+("centreSelectIcon cen_"+b)+"'>"+this.centreOptions[b]+"</option>");b=$("#centre_select");b.append(a.join(""));b.iconselectmenu().iconselectmenu("menuWidget").addClass("ui-menu-icons customicons");b.iconselectmenu({width:"60px",change:$.proxy(function(a,b){setCentre(b.item.value)},this)});b.val(this.currentCentreId).iconselectmenu("refresh",
!0)};iev.embryoviewer.prototype.setActiveModalityButtons=function(){for(var a in this.centreData[this.currentCentreId])1>this.objSize(this.centreData[this.currentCentreId][a].vols.mutant)?$("#modality_stage input[id^="+a+"]:radio").attr("disabled",!0):$("#modality_stage input[id^="+a+"]:radio").attr("disabled",!1)};iev.embryoviewer.prototype.buildUrl=function(a){a.volume_url=this.IMAGE_SERVER+a.cid+"/"+a.lid+"/"+a.gid+"/"+a.sid+"/"+a.pid+"/"+a.qid+"/"+a.imageForDisplay;return a};
iev.embryoviewer.prototype.bookmarkConfigure=function(){if(!this.bookmarkReady){"off"===this.bookmarkData.s&&$("#X_check").trigger("click");"off"===this.bookmarkData.c&&$("#Y_check").trigger("click");"off"===this.bookmarkData.a&&$("#Z_check").trigger("click");"vertical"===this.bookmarkData.orientation&&$("#orientation_button").trigger("click");this.zoomBy(this.bookmarkData.zoom);if(this.bookmarkData.h){var a=$("#viewHeightSlider");a.slider("value",this.bookmarkData.h);a.slider("option","slide").call(a,
null,{value:this.bookmarkData.h})}this.bookmarkReady=!0}};
iev.embryoviewer.prototype.generateBookmark=function(){var a=window.location.href.split("?")[0],b=this.ortho.X.visible?"on":"off",c=this.ortho.Y.visible?"on":"off",d=this.ortho.Z.visible?"on":"off";return a+"?"+this.bookmarkData.mode+"="+this.bookmarkData.gene+"&mod="+this.mutView+"&h="+this.currentViewHeight+"&wt="+this.wtView.getCurrentVolume().animalName+"&mut="+mutView.getCurrentVolume().animalName+"&s="+b+"&c="+c+"&a="+d+"&wx="+this.wtView.getIndex("X")+"&wy="+this.wtView.getIndex("Y")+"&wz="+
this.wtView.getIndex("Z")+"&mx="+this.mutView.getIndex("X")+"&my="+this.mutView.getIndex("Y")+"&mz="+this.mutView.getIndex("Z")+"&wl="+this.wtView.getBrightnessLower()+"&wu="+this.wtView.getBrightnessUpper()+"&ml="+this.mutView.getBrightnessLower()+"&mu="+this.mutView.getBrightnessUpper()+"&o="+this.currentOrientation+"&zoom="+currentZoom};
iev.embryoviewer.prototype.zoomBy=function(a){if(0>a)for(;0>a;)setTimeout(function(){zoomViewsOut()},1E3),a++;if(0<a)for(;0<a;)setTimeout(function(){zoomViewsIn()},1E3),a--};iev.embryoviewer.prototype.zoomViewsIn=function(){this.wtView.zoomIn();this.mutView.zoomIn()};iev.embryoviewer.prototype.zoomViewsOut=function(){this.wtView.zoomOut();this.mutView.zoomOut()};
iev.embryoviewer.prototype.scaleOrthogonalViews=function(){for(var a=0;a<this.views.length;++a)this.views[a].rescale(this.scales.currentBarSize);window.dispatchEvent(new Event("resize"))};iev.embryoviewer.prototype.beforeReady=function(){$("#modality_stage :input").prop("disabled",!0);$("#modality_stage").buttonset("refresh")};
iev.embryoviewer.prototype.onReady=function(){this.setActiveModalityButtons();$("#modality_stage").buttonset("refresh");this.currentZoom=0;this.bookmarkConfigure();$("#scale_select").val(this.scales.currentBarSize).selectmenu("refresh");$(".scale_text").text($("#scale_select").find(":selected").text());$(".linkCheck").change(function(a){$(a.target).hasClass("X")?this.linkViews("X",a.currentTarget.checked):$(a.target).hasClass("Y")?this.linkViews("Y",a.currentTarget.checked):$(a.target).hasClass("Z")&&
this.linkViews("Z",a.currentTarget.checked)}.bind(this));this.scaleOrthogonalViews();$(".scale_outer").draggable()};iev.embryoviewer.prototype.loadViewers=function(){this.localStorage=new iev.LocalStorage(function(){this.afterLoadingLocalStorage(this.container)}.bind(this))};
iev.embryoviewer.prototype.afterLoadingLocalStorage=function(){var a,b;for(b in this.volorder)if(a=this.volorder[b],0<this.objSize(this.centreData[this.currentCentreId][a].vols.mutant)){var c=this.centreData[this.currentCentreId][a].vols.wildtype,d=this.centreData[this.currentCentreId][a].vols.mutant;break}this.currentModality=a;$("#modality_stage input[id^="+a+"]:radio").attr("checked",!0);0<this.objSize(c)&&(a={specimen:this.bookmarkData.wt},this.wtView=new iev.specimenview(c,"wt",this.container,
this.WILDTYPE_COLONYID,this.sliceChange.bind(this),a,this.loadedCb.bind(this),this.localStorage),this.views.push(this.wtView));c={specimen:this.bookmarkData.mut};this.mutView=new iev.specimenview(d,"mut",this.container,this.queryId,this.sliceChange.bind(this),c,this.loadedCb.bind(this),this.localStorage);this.views.push(this.mutView);this.centreSelector()};iev.embryoviewer.prototype.loadedCb=function(){for(var a=0;a<this.views.length;a++)if(!this.views[a].isReady())return;this.onReady()};
iev.embryoviewer.prototype.setCentre=function(a){this.currentCentreId=a;this.setStageModality(this.currentModality)};
iev.embryoviewer.prototype.setStageModality=function(a){this.beforeReady();this.currentModality=a;if("undefined"!==typeof this.wtView){var b=this.centreData[this.currentCentreId][a].vols.wildtype;0<Object.keys(b).length?($("#wt").show(),this.wtView.updateData(b),this.wtView.reset()):$("#wt").hide()}"undefined"!==typeof this.mutView&&(a=this.centreData[this.currentCentreId][a].vols.mutant,0<Object.keys(a).length?($("#mut").show(),this.mutView.updateData(a),this.mutView.reset()):$("#mut").hide())};
iev.embryoviewer.prototype.sliceChange=function(a,b,c){for(var d=0;d<this.views.length;d++)this.views[d].id!==a&&("X"===b&&this.ortho.X.linked?this.views[d].setXindex(c):"Y"===b&&this.ortho.Y.linked?this.views[d].setYindex(c):"Z"===b&&this.ortho.Z.linked&&this.views[d].setZindex(c))};
iev.embryoviewer.prototype.linkViews=function(a,b){var c,d;$("."+a).prop("checked",b);ortho[a].linked=b;for(var e=0;e<this.views.length;e++)"wt"===this.views[e].id?c=this.views[e].getIndex(a):"mut"===this.views[e].id&&(d=this.views[e].getIndex(a));for(e=0;e<this.views.length;e++)"mut"===this.views[e].id&&this.views[e].setIdxOffset(a,c-d)};iev.embryoviewer.prototype.setLowPowerState=function(a){for(var b=0;b<this.views.length;b++)this.views[b].setLowPowerState(a)};
iev.embryoviewer.prototype.getNewFileName=function(a){var b=a.sex;"No data"===b&&(b="undeterminedSex");var c=this.sanitizeFileName(a.geneSymbol);a=this.sanitizeFileName(a.animalName);return b+"_"+a+"_"+c};
iev.embryoviewer.prototype.attachEvents=function(){$("#low_power_check").button().click(function(a){setLowPowerState(a.currentTarget.checked)}.bind(this));$("#help_link").button({icons:{primary:"ui-icon-help"}}).css({width:"30"});$("#reset").click($.proxy(function(){for(var a=0;a<this.views.length;a++)this.views[a].reset()},this));$("#invertColours").click(function(a){a.preventDefault();var b;$(a.target).hasClass("ievgrey")?($(a.target).removeClass("ievgrey"),$(a.target).addClass("ievInvertedGrey"),
$(".sliceView").css("background-color","#FFFFFF"),$(".sliceControls").css("background-color","#FFFFFF"),$(".scale_text").css("color","#000000"),$(".scale").css("background-color","#000000"),b=!0):$(a.target).hasClass("ievInvertedGrey")&&($(a.target).removeClass("ievInvertedGrey"),$(a.target).addClass("ievgrey"),$(".sliceView").css("background-color","#000000"),$(".sliceControls").css("background-color","#000000"),$(".scale_text").css("color","#FFFFFF"),$(".scale").css("background-color","#FFFFFF"),
b=!1);for(a=0;a<this.views.length;a++)this.views[a].invertColour(b)}.bind(this));$("#zoomIn").button().click($.proxy(function(){for(var a=0;a<this.views.length;a++)this.views[a].zoomIn();this.currentZoom++},this));$("#zoomOut").button().click($.proxy(function(){for(var a=0;a<this.views.length;a++)if(!this.views[a].zoomOut())return;this.currentZoom--},this));$("#download").click(function(a){a.preventDefault();this.setupDownloadTable(a)}.bind(this));$("#createBookmark").click(function(a){this.bookmarkReady&&
(a.preventDefault(),a=generateBookmark(),window.prompt("Bookmark created!\nCopy to clipboard (Ctrl/Cmd+C + Enter)",a))});$("#modality_stage").buttonset();$("#orthogonal_views_buttons").buttonset();$("#orientation_button").click(function(a){a.preventDefault();$(a.target).hasClass("vertical")?($(a.target).removeClass("vertical"),$(a.target).addClass("horizontal"),this.setViewOrientation("horizontal"),this.currentOrientation="horizontal"):($(a.target).removeClass("horizontal"),$(a.target).addClass("vertical"),
this.setViewOrientation("vertical"),this.currentOrientation="vertical")}.bind(this));$(".toggle_slice").change(function(){for(var a=["X_check","Y_check","Z_check"],b=0,c=0;c<a.length;c++)$("#"+a[c]).is(":checked")?(this.ortho[a[c].charAt(0)].visible=!0,b++):this.ortho[a[c].charAt(0)].visible=!1;for(c=0;c<this.views.length;c++)this.views[c].setVisibleViews(this.ortho,b,this.horizontalView);window.dispatchEvent(new Event("resize"));this.currentZoom=0}.bind(this));$("#scale_visible").change(function(a){$(a.currentTarget).is(":checked")?
($("#scale_select").selectmenu("enable"),$(".scale_outer").css({visibility:"visible"})):($("#scale_select").selectmenu("disable"),$(".scale_outer").css({visibility:"hidden"}))}.bind(this));$(".modality_button").change(function(a){this.setStageModality(a.currentTarget.id)}.bind(this));$(".button").button();$("#viewHeightSlider").slider({min:200,max:1920,value:500,slide:$.proxy(function(a,b){this.currentViewHeight=b.value;$(".sliceWrap").css("height",b.value);this.scaleOrthogonalViews();var c=document.createEvent("UIEvents");
c.initUIEvent("resize",!0,!1,window,0);window.dispatchEvent(c)},this)});this.downloadTableRowSource=$("#downloadTableRowTemplate").html()};
iev.embryoviewer.prototype.setupDownloadTable=function(){var a=$("#download_dialog").dialog({title:"Select volumes for download",resizable:!0,autoOpen:!1,modal:!0,hide:"fade",width:700,height:550,position:{my:"left bottom",at:"left top",of:$("#top_bar")}}),b=Handlebars.compile(this.downloadTableRowSource);a.load("download_dialog.html",function(){for(var c in this.centreData[this.currentCentreId])if(c===this.currentModality){var d=this.centreData[this.currentCentreId][this.currentModality].vols;console.log("vols",
d);for(var e=[],f=0;f<this.views.length;++f)e.push(this.views[f].getCurrentVolume().volume_url);for(var j in d.mutant){var g=d.mutant[j],f=this.getNewFileName(g),g=g.volume_url,h="#FFFFFF";-1<$.inArray(g,e)&&(h="#ef7b0b");f={remotePath:g+";"+f,volDisplayName:f,bg:h};$("#mutant_table tbody").append(b(f))}for(j in d.wildtype)g=d.wildtype[j],f=this.getNewFileName(g),g=g.volume_url,h="#FFFFFF",-1<$.inArray(g,e)&&(h="#ef7b0b"),f={remotePath:g+";"+f,volDisplayName:f,bg:h},$("#wt_table tbody").append(b(f))}a.dialog("open");
$("#download_dialog_button").click(function(){a.dialog("close");this.getZippedVolumes()}.bind(this))}.bind(this))};
iev.embryoviewer.prototype.getZippedVolumes=function(){for(var a="",b=$("#wt_table").find('input[type="checkbox"]:checked'),c=0;c<b.length;++c)var d=b[c].name,a=a+(d+",");b=$("#mutant_table").find('input[type="checkbox"]:checked');for(c=0;c<b.length;++c)d=b[c].name,a+=d+",";a="rest/zip?vol="+a;this.progressIndicator("preparing zip");$.fileDownload(a,{successCallback:function(){this.progressStop()}.bind(this),failCallback:function(){alert("There was an error downloading the images")}})};
iev.embryoviewer.prototype.progressStop=function(){this.spinner.stop();$("#progressMsg").empty()};iev.embryoviewer.prototype.progressIndicator=function(a){var b=document.getElementById("progressSpin");this.spinner=(new Spinner(this.spinnerOpts)).spin(b);$("#progressMsg").text(a)};iev.embryoviewer.prototype.sanitizeFileName=function(a){return a.replace(/[|&;$%@"<>()+,\/]/g,"")};iev.embryoviewer.prototype.basename=function(a){return a.split(/[\\/]/).pop()};
iev.embryoviewer.prototype.objSize=function(a){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b};iev.embryoviewer.prototype.setBreadCrumb=function(){var a="/data/genes/"+this.mgi;$("#ievBreadCrumbGene").html(this.gene_symbol).attr("href",a)};
iev.embryoviewer.prototype.setInitialViewerHeight=function(){var a=$(window.top).innerHeight(),b=$("#help").outerHeight(),c=$("#header").outerHeight(),d=$("#iev_subHeader").outerHeight(),e=$("#ievControlsWrap").outerHeight();this.availableViewHeight=Math.round((a-c-d-e-b-76)/2);console.log(a,c,d,e);$("<style type='text/css'> .sliceWrap{height:"+(200>this.availableViewHeight?200:this.availableViewHeight)+"px;}</style>").appendTo("head")};
iev.embryoviewer.prototype.setViewOrientation=function(a){"vertical"===a&&(this.horizontalView=!0,$(".specimen_view").css({"float":"left",width:"50%",clear:"none"}),$(".sliceWrap").css({width:"100%"}),window.dispatchEvent(new Event("resize")));if("horizontal"===a){this.horizontalView=!1;a=0;for(var b in this.ortho)this.ortho[b].visible&&++a;$(".specimen_view").css({"float":"none",width:"100%",clear:"both"});$(".sliceWrap").css({width:String(100/a)+"%"});window.dispatchEvent(new Event("resize"))}};
iev.embryoviewer.prototype.setScaleSelect=function(){$("#scale_select").append(this.scaleLabels().join("")).selectmenu({width:80,height:20,change:$.proxy(function(a,b){this.scales.currentBarSize=b.item.value;$(".scale_text").text(b.item.label);this.scaleOrthogonalViews()},this)})};
iev.embryoviewer.prototype.isInternetExplorer=function(){if(0<window.navigator.userAgent.indexOf("MSIE ")||navigator.userAgent.match(/Trident.*rv\:11\./)){var a=$("#ie_warning_template").html(),a=Handlebars.compile(a);$("#"+div).append(a(data));return!0}return!1};
iev.embryoviewer.prototype.catchXtkLoadError=function(){window.onerror=function(a,b,c){console.log(a,b,c);if("Uncaught Error: input buffer is broken"===a||"Uncaught Error: Loading failed"===a||"Uncaught Error: invalid file signature"===a)for(a=0;a<this.views.length;++a)this.views[a].caughtXtkLoadError()}};iev.specimenview=function(a,b,c,d,e,f,j,g){console.log("id",b);this.localStorage=g;this.xtkLoadError=!1;this.queryColonyId=d;this.config=f;this.indexCB=e;this.id=b;this.viewContainer=c;this.volumeData=a;this.readyCB=j;this.$xContainer;this.$zContainer;this.$xWrap;this.$yWrap;this.$zWrap;this.$xSlider;this.$ySlider;this.$zSlider;this.$windowLevel;this.xRen;this.yRen;this.zRen;this.volume;this.scaleBarSize;this.lowPower=!1;this.windowLevel="windowLevel_"+b;this.vselector="volumeSelector_"+b;this.inverted=
!1;this.zOffset=this.yOffset=this.xOffset=0;this.ready=!1;this.progressSpinner;console.log(f,b);this.contrast=f.specimen.brightness;this.WILDTYPE_COLONYID="baseline";this.currentVolume=a[Object.keys(a)[0]];this.bookmarkHasVolume=!1;if(f.specimen)for(var h in a)if(a.hasOwnProperty(h)&&(b=a[h],b.animalName===f.specimen.name)){this.currentVolume=b;this.bookmarkHasVolume=!0;break}this.ICONS_DIR="images/centre_icons/";this.IMG_DIR="images/";this.FEMALE_ICON="female.png";this.MALE_ICON="male.png";this.NDSEX_ICON=
"unknown_sex.png";this.HOM_ICON="hom.png";this.HEMI_ICON=this.HET_ICON="het.png";this.WT_ICON="wildtype.png";this.specimenMetaTemplateSource=$("#specimenMetdataTemplate").html();this.centreIcons={1:"logo_Bcm.png",3:"logo_Gmc.png",4:"logo_H.png",6:"logo_Ics.png",7:"logo_J.png",8:"logo_Tcp.png",9:"logo_Ning.png",10:"logo_Rbrc.png",11:"logo_Ucd.png",12:"logo_Wtsi.png"};this.spinner;this.spinnerOpts={lines:8,length:6,width:6,radius:8,scale:1,corners:1,color:"#ef7b0b",opacity:0.2,rotate:0,direction:1,
speed:1,trail:50,fps:10,zIndex:2E9,className:"spinner",top:"20px",shadow:!1,hwaccel:!1,position:"relative"};this.monthNames="Jan Feb Mar April May June July Aug Sep Oct Nov Dec".split(" ");this.createHTML();this.updateVolumeSelector();this.jQuerySelectors();this.setupRenderers();this.drawScaleBar()};iev.specimenview.prototype.updateData=function(a){this.volumeData=a;this.replaceVolume(this.volumeData[Object.keys(this.volumeData)[0]].volume_url);this.updateVolumeSelector()};
iev.specimenview.prototype.update=function(){this.invertColour(this.inverted);this.drawScaleBar();this.showMetadata()};
iev.specimenview.prototype.updateVolumeSelector=function(){$.widget("custom.iconselectmenu",$.ui.selectmenu,{_renderItem:function(a,b){var c=$("<li>",{text:b.label});b.disabled&&c.addClass("ui-state-disabled");$("<span>",{style:b.element.attr("data-style"),"class":"ui-icon "+b.element.attr("data-class")}).appendTo(c);return c.appendTo(a)}});$("#"+this.vselector).find("option").remove().end();var a=[],b;for(b in this.volumeData){var c=this.volumeData[b].volume_url,d=this.volumeData[b].sex.toLowerCase(),
e=this.volumeData[b].zygosity.toLowerCase();"no data"===d&&(d="no_data");d=this.volumeData[b].colonyId===this.WILDTYPE_COLONYID?"specimenSelectIcon "+d+"_wildtype":"specimenSelectIcon "+d+"_"+e;e=this.volumeData[b].animalName.substring(0,25);c===this.currentVolume.volume_url?(a.push("<option value='"+c+"' data-class='"+d+"' selected>"+e+"</option>"),this.bookmarkHasVolume=!1):a.push("<option value='"+c+"' data-class='"+d+"'>"+e+"</option>")}$("#"+this.vselector).append(a.join(""));$("#"+this.vselector).iconselectmenu().iconselectmenu("menuWidget").addClass("ui-menu-icons customicons");
$("#"+this.vselector).iconselectmenu({change:$.proxy(function(a,b){this.bookmarkHasVolume||this.replaceVolume(b.item.value)},this)}).iconselectmenu("refresh")};
iev.specimenview.prototype.showMetadata=function(){var a=new Date(this.currentVolume.experimentDate),b=this.monthNames[a.getMonth()],b=b+(" "+a.getDate()),b=b+(" "+a.getFullYear()),c;"female"===this.currentVolume.sex.toLowerCase()?c=this.IMG_DIR+this.FEMALE_ICON:"male"===this.currentVolume.sex.toLowerCase()?c=this.IMG_DIR+this.MALE_ICON:"no data"===this.currentVolume.sex.toLowerCase()&&(c=this.IMG_DIR+this.NDSEX_ICON);var d;if(this.currentVolume.colonyId===this.WILDTYPE_COLONYID)d=this.WT_ICON;else switch(this.currentVolume.zygosity.toLowerCase()){case "homozygous":console.log("hello");
d=this.HOM_ICON;break;case "heterozygous":console.log("hettttt");d=this.HET_ICON;break;case "hemizygous":console.log("hemiiiii"),d=this.HEMI_ICON}a=this.IMG_DIR+d;d="";this.centreIcons.hasOwnProperty(this.currentVolume.cid)&&(d=this.ICONS_DIR+this.centreIcons[this.currentVolume.cid]);b={animalId:this.currentVolume.animalName,date:b,sexIconPath:c,zygIconPath:a,centreLogoPath:d};c=Handlebars.compile(this.specimenMetaTemplateSource);b=$(c(b));$("#metadata_"+this.id).empty();$("#metadata_"+this.id).append(b)};
iev.specimenview.prototype.setContrastSlider=function(){this.$windowLevel.slider({range:!0,min:parseInt(this.volume.min),max:parseInt(this.volume.max),step:Math.ceil((this.volume.max-this.volume.min)/256),values:[parseInt(this.volume.windowLow),parseInt(this.volume.windowHigh)],slide:$.proxy(function(a,b){this.volume.windowLow=b.values[0];this.volume.windowHigh=b.values[1];this.volume.modified(!0)},this)})};
iev.specimenview.prototype.setBookmarkContrast=function(){var a=parseInt(this.volume.windowLow);null!==this.contrast.lower&&(a=Math.max(this.contrast.lower,parseInt(this.volume.windowLow)));var b=parseInt(this.volume.windowHigh);null!==this.contrast.upper&&(b=Math.min(this.contrast.upper,parseInt(this.volume.windowHigh)));this.volume.windowLow=a;this.volume.windowHigh=b;this.volume.modified(!1);this.$windowLevel.slider("option","values",[this.volume.windowLow,this.volume.windowHigh])};
iev.specimenview.prototype.reset=function(){this.xRen.resetViewAndRender();this.yRen.resetViewAndRender();this.zRen.resetViewAndRender();var a=this.volume.dimensions;this.volume.indexX=Math.floor((a[0]-1)/2);this.volume.indexY=Math.floor((a[1]-1)/2);this.volume.indexZ=Math.floor((a[2]-1)/2);this.$xSlider.slider("value",this.volume.indexX);this.$ySlider.slider("value",this.volume.indexY);this.$zSlider.slider("value",this.volume.indexZ);this.$windowLevel.slider("option","values",[this.volume.windowLow,
this.volume.windowHigh]);$(".scale_outer").css({height:"100%",bottom:"30px",width:"20px",position:"relative",left:"20px","z-index":900});this.update()};
iev.specimenview.prototype.createHTML=function(){var a=$("#"+this.viewContainer);if(!(1>this.objSize(this.volumeData)&&null!==this.queryColonyId)){var b={id:this.id},c=$("#specimen_view_template").html(),c=Handlebars.compile(c),c=$(c(b));c.append(this.controls_tab());c.append(this.createSliceView("X"));c.append(this.createSliceView("Y"));c.append(this.createSliceView("Z"));var d=$("#progress_template").html(),d=Handlebars.compile(d),b=$(d(b));c.append(b);this.spinner=(new Spinner(this.spinnerOpts)).spin();
b.find(".ievLoadingMsg").append(this.spinner.el);a.append(c)}};iev.specimenview.prototype.progressStop=function(){this.spinner.stop();$("#progressMsg").empty()};iev.specimenview.prototype.createSliceView=function(a){a={sliceWrapId:"sliceWrap_"+a+"_"+this.id,sliceContainerID:a+"_"+this.id,viewSliceClasss:"slice"+a,sliderId:"slider_"+a+"_"+this.id,sliderClass:"slider"+a,orientation:a,id:this.id,scaleId:"scale_"+a+this.id,scaleTextId:"scaletext_"+a+this.id};var b=$("#slice_view_template").html();return Handlebars.compile(b)(a)};
iev.specimenview.prototype.jQuerySelectors=function(){this.$xContainer=$("#X_"+this.id);this.$yContainer=$("#Y_"+this.id);this.$zContainer=$("#Z_"+this.id);this.$xSlider=$("#slider_X_"+this.id);this.$ySlider=$("#slider_Y_"+this.id);this.$zSlider=$("#slider_Z_"+this.id);this.$xWrap=$("#sliceWrap_X_"+this.id);this.$yWrap=$("#sliceWrap_Y_"+this.id);this.$zWrap=$("#sliceWrap_Z_"+this.id);this.$windowLevel=$("#"+this.windowLevel)};
iev.specimenview.prototype.controls_tab=function(){var a={id:this.id,controlsButtonsId:"controlsButtons_"+this.id,selectorWrapId:"selectorWrap_"+this.id,vselectorId:this.vselector,windowLevelId:this.windowLevel},b=$("#slice_controls_template").html();return Handlebars.compile(b)(a)};iev.specimenview.prototype.zoomIn=function(){this.xRen.camera.zoomIn(!1);this.yRen.camera.zoomIn(!1);this.zRen.camera.zoomIn(!1);this.drawScaleBar()};
iev.specimenview.prototype.zoomOut=function(){if(1>this.xRen.normalizedScale||1>this.yRen.normalizedScale||1>this.zRen.normalizedScale)return!1;this.xRen.camera.zoomOut(!1);this.yRen.camera.zoomOut(!1);this.zRen.camera.zoomOut(!1);this.drawScaleBar();return!0};
iev.specimenview.prototype.drawScaleBar=function(){setTimeout(function(){this.drawScale(this.yRen,"scale_Y"+this.id,"scaletext_Y"+this.id);this.drawScale(this.zRen,"scale_Z"+this.id,"scaletext_Z"+this.id);this.drawScale(this.xRen,"scale_X"+this.id,"scaletext_X"+this.id)}.bind(this),20)};
iev.specimenview.prototype.drawScale=function(a,b,c){var d=$(".scale_outer_"+this.id);null===this.currentVolume.rescaledPixelsize||0===this.currentVolume.rescaledPixelsize?d.hide():(d.show(),a=this.scaleBarSize/this.currentVolume.rescaledPixelsize*a.normalizedScale,d=($(".scale_outer").height()-a)/2,$("#"+b).css({height:a,width:"2px",position:"absolute",top:d}),$("#"+c).css({position:"absolute",top:d-20,"font-size":"10px"}))};iev.specimenview.prototype.rescale=function(a){this.scaleBarSize=a;this.drawScaleBar()};
iev.specimenview.prototype.getVolume=function(){return this.volume};
iev.specimenview.prototype.replaceVolume=function(a){var b={id:this.id},c=$("#"+this.id),d=$("#progress_template").html(),d=Handlebars.compile(d),b=$(d(b));c.append(b);this.spinner=(new Spinner(this.spinnerOpts)).spin();b.find(".ievLoadingMsg").append(this.spinner.el);"undefined"!==typeof this.xRen&&(this.xRen.destroy(),delete this.xRen);"undefined"!==typeof this.yRen&&(this.yRen.destroy(),delete this.yRen);"undefined"!==typeof this.zRen&&(this.zRen.destroy(),delete this.zRen);"undefined"!==typeof this.volume&&
(this.volume.destroy(),delete this.volume);this.currentVolume=this.volumeData[a];this.setupRenderers()};
iev.specimenview.prototype.setupRenderers=function(){this.ready=!1;1>this.objSize(this.volumeData)||(this.xRen=new X.renderer2D,this.xRen.config.PROGRESSBAR_ENABLED=!1,this.xRen.firstRender=!0,this.xRen.afterRender=function(){this.xRen.firstRender&&(this.xRen.resetViewAndRender(),this.xRen.firstRender=!1,this.xtk_showtime())}.bind(this),this.xRen.onShowtime=function(){this.setContrastSlider();this.setReady()}.bind(this),this.xRen.container=this.$xContainer.get(0),this.xRen.orientation="X",this.xRen.init(),
this.overrideRightMouse(this.xRen),this.yRen=new X.renderer2D,this.yRen.config.PROGRESSBAR_ENABLED=!1,this.yRen.container=this.$yContainer.get(0),this.yRen.orientation="Y",this.yRen.init(),this.overrideRightMouse(this.yRen),this.zRen=new X.renderer2D,this.zRen.config.PROGRESSBAR_ENABLED=!1,this.zRen.container=this.$zContainer.get(0),this.zRen.orientation="Z",this.zRen.init(),this.overrideRightMouse(this.zRen),this.volume=new X.volume,this.volume.file="dummy.nrrd",this.localStorage.getVolume(this.currentVolume.volume_url,
new Date(this.currentVolume.lastUpdate),this.onFetchedData.bind(this)))};iev.specimenview.prototype.onFetchedData=function(a){if(a)this.volume.filedata=a,this.xRen.add(this.volume),this.checkLoading(),this.xRen.render();else{$("#ievLoading"+this.id).remove();var b={geneOrColonyId:this.queryColonyId,animalId:this.currentVolume.animalName};a=$("#"+this.id);var c=$("#dataNotFoundTemplate").html(),b=Handlebars.compile(c)(b);a.append(b)}};
iev.specimenview.prototype.checkLoading=function(){var a=setInterval(function(){console.log("carrots");if(this.ready)clearInterval(a);else if(this.xtkLoadError){$("#ievLoading"+this.id).remove();var b={colonyId:this.currentVolume.colonyId,animalId:this.currentVolume.animalName},c=$("#"+this.id),d=$("#dataNotFoundTemplate").html(),b=Handlebars.compile(d)(b);c.append(b);clearInterval(a);this.localStorage.removeVolume(this.currentVolume.volume_url);console.log(this.currentVolume.volume_url);this.xtkLoadError=
!1}}.bind(this),5E3)};iev.specimenview.prototype.overrideRightMouse=function(a){a.interactor.onMouseDown=function(a,c,d){d&&console.log("mousy R")}};iev.specimenview.prototype.setReady=function(){$("#ievLoading"+this.id).remove();$("#noData").remove();this.ready=!0;this.readyCB()};iev.specimenview.prototype.isReady=function(){return this.ready};
iev.specimenview.prototype.invertColour=function(a){this.volume&&((this.inverted=a)?(this.volume.maxColor=[0,0,0],this.volume.minColor=[1,1,1],$("#"+this.id+"> .sliceView").css("background-color","#FFFFFF"),this.volume.indexX++,this.volume.indexY++,this.volume.indexZ++):(this.volume.maxColor=[1,1,1],this.volume.minColor=[0,0,0],$("#"+this.id+"> .sliceView").css("background-color","#000000"),this.volume.indexX--,this.volume.indexY--,this.volume.indexZ--))};
iev.specimenview.prototype.sliceChange=function(a,b,c){"X"===b?this.indexCB(a,b,c+this.xOffset):"Y"===b?this.indexCB(a,b,c+this.yOffset):"Z"===b&&this.indexCB(a,b,c+this.zOffset)};iev.specimenview.prototype.setLowPowerState=function(a){this.lowPower=a};
iev.specimenview.prototype.updateSliders=function(a){a.interactor.mousemoveEvent.shiftKey?(this.$xSlider.slider("value",this.volume.indexX),this.$ySlider.slider("value",this.volume.indexY),this.$zSlider.slider("value",this.volume.indexZ),this.sliceChange(this.id,"X",this.volume.indexX),this.sliceChange(this.id,"Y",this.volume.indexY),this.sliceChange(this.id,"Z",this.volume.indexZ)):a.interactor.leftButtonDown&&this.$windowLevel.slider("option","values",[this.volume.windowLow,this.volume.windowHigh])};
iev.specimenview.prototype.makeIndexSlider=function(a,b,c){var d="index"+b;a.slider({disabled:!1,range:"min",min:0,max:c,value:this.volume[d],slide:function(a,c){this.volume&&!this.lowPower&&(this.volume[d]=c.value,this.sliceChange(this.id,b,this.volume[d]))}.bind(this),stop:function(a,c){this.volume&&this.lowPower&&(this.volume[d]=c.value,this.sliceChange(this.id,b,this.volume[d]))}.bind(this)})};
iev.specimenview.prototype.xtk_showtime=function(){this.yRen.add(this.volume);this.yRen.render();this.zRen.add(this.volume);this.zRen.render();var a=this.volume.dimensions,b=this.config.specimen.pos;this.volume.indexX=(isNaN(b.x),b.x);this.volume.indexY=(isNaN(b.y),b.y);this.volume.indexZ=(isNaN(b.z),b.z);this.makeIndexSlider(this.$xSlider,"X",a[0]-1);this.makeIndexSlider(this.$ySlider,"Y",a[1]-1);this.makeIndexSlider(this.$zSlider,"Z",a[2]-1);this.xRen.interactor.onMouseWheel=function(){this.$xSlider.slider({value:this.volume.indexX});
this.sliceChange(this.id,"X",this.volume.indexX)}.bind(this);this.yRen.interactor.onMouseWheel=function(){this.$ySlider.slider({value:this.volume.indexY});this.sliceChange(this.id,"Y",this.volume.indexY)}.bind(this);this.zRen.interactor.onMouseWheel=function(){this.$zSlider.slider({value:this.volume.indexZ});this.sliceChange(this.id,"Z",this.volume.indexZ)}.bind(this);this.xRen.interactor.onMouseMove=function(a){this.updateSliders(this.xRen,a)}.bind(this);this.yRen.interactor.onMouseMove=function(a){this.updateSliders(this.yRen,
a)}.bind(this);this.zRen.interactor.onMouseMove=function(a){this.updateSliders(this.zRen,a)}.bind(this);this.yRen.interactor.rightButtonDown=function(){};this.setBookmarkContrast();this.update()};iev.specimenview.prototype.setXindex=function(a){this.volume.indexX=a-this.xOffset;this.$xSlider.slider("value",this.volume.indexX)};iev.specimenview.prototype.setYindex=function(a){this.volume.indexY=a-this.yOffset;this.$ySlider.slider("value",this.volume.indexY)};
iev.specimenview.prototype.setZindex=function(a){this.volume.indexZ=a-this.zOffset;this.$zSlider.slider("value",this.volume.indexZ)};iev.specimenview.prototype.getBrightnessLower=function(){return this.volume.windowLow};iev.specimenview.prototype.getBrightnessUpper=function(){return this.volume.windowHigh};iev.specimenview.prototype.getIndex=function(a){if("X"===a)return this.volume.indexX;if("Y"===a)return this.volume.indexY;if("Z"===a)return this.volume.indexZ};
iev.specimenview.prototype.setIdxOffset=function(a,b){"X"===a&&(this.xOffset=b);"Y"===a&&(this.yOffset=b);"Z"===a&&(this.zOffset=b)};iev.specimenview.prototype.getDimensions=function(){return this.volume.dimensions};iev.specimenview.prototype.getCurrentVolume=function(){return this.currentVolume};
iev.specimenview.prototype.setVisibleViews=function(a,b,c){b=c?100:String(100/b);a.X.visible?(this.$xWrap.show(),this.$xWrap.width(b+"%")):this.$xWrap.hide();a.Y.visible?(this.$yWrap.show(),this.$yWrap.width(b+"%")):this.$yWrap.hide();a.Z.visible?(this.$zWrap.show(),this.$zWrap.width(b+"%")):this.$zWrap.hide()};iev.specimenview.prototype.basename=function(a){return a.split(/[\\/]/).pop()};iev.specimenview.prototype.objSize=function(a){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b};
iev.specimenview.prototype.getData=function(){};iev.specimenview.prototype.caughtXtkLoadError=function(){this.xtkLoadError=!0};goog.exportSymbol("iev.specimenview.prototype.updateData",iev.specimenview.prototype.updateData);goog.exportSymbol("iev.specimenview.prototype.reset",iev.specimenview.prototype.reset);goog.exportSymbol("iev.specimenview.prototype.getCurrentVolume",iev.specimenview.prototype.getCurrentVolume);goog.exportSymbol("iev.specimenview.prototype.getIndex",iev.specimenview.prototype.getIndex);
goog.exportSymbol("iev.specimenview.getBrightnessLower",iev.specimenview.getBrightnessLower);goog.exportSymbol("iev.specimenview.getBrightnessupper",iev.specimenview.getBrightnessUpper);goog.exportSymbol("iev.specimenview.prototype.zoomIn",iev.specimenview.prototype.zoomIn);goog.exportSymbol("iev.specimenview.prototype.zoomOut",iev.specimenview.prototype.zoomOut);goog.exportSymbol("iev.specimenview.prototype.getIndex",iev.specimenview.prototype.getIndex);
