// This file was autogenerated by X/lib/google-closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../../iev/iev.js', ['iev'], []);
goog.addDependency('../../../../../iev/localstorage.js', ['iev.LocalStorage'], []);
goog.addDependency('../../../../../iev/download.js', ['iev.Download'], []);
goog.addDependency('../../../../../iev/embryoviewer.js', ['iev.embryoviewer'], ['iev.LocalStorage', 'iev.specimenview']);
goog.addDependency('../../../../../iev/specimenview.js', ['iev.specimenview'], []);
goog.addDependency('../../../../../iev/embryo.js', ['iev.embryo'], ['iev.embryoviewer']);
goog.addDependency('../../../../../iev/filegetter.js', ['iev.fileGetter'], ['iev.embryoviewer']);

