var iev={specimenview:function(a,b,c,d,g,e,h){"undefined"===typeof dcc&&(dcc={});this.queryColonyId=d;this.config=e;this.indexCB=g;this.id=b;this.viewContainer=c;this.volumeData=a;this.readyCB=h;this.$xContainer;this.$zContainer;this.$xWrap;this.$yWrap;this.$zWrap;this.$xSlider;this.$ySlider;this.$zSlider;this.$windowLevel;this.xRen;this.yRen;this.zRen;this.volume;this.hasLabelmap=!1;this.currentLabelmap="jacobian";this.scaleBarSize;this.lowPower=!1;this.windowLevel="windowLevel_"+b;this.overlayControl=
"overlayControl_"+b;this.vselector="volumeSelector_"+b;this.zOffset=this.yOffset=this.xOffset=0;this.ready=!1;this.progressSpinner;this.contrast=e.specimen.brightness;this.WILDTYPE_COLONYID="baseline";this.currentVolume=a[Object.keys(a)[0]];this.bookmarkHasVolume=!1;if("null"!==e.specimen.name)for(var f in a)if(a.hasOwnProperty(f)&&(b=a[f],b.animalName===e.specimen.name)){this.currentVolume=b;this.bookmarkHasVolume=!0;break}this.ICONS_DIR="images/centre_icons/";this.IMG_DIR="images/";this.FEMALE_ICON=
"female.png";this.MALE_ICON="male.png";this.HOM_ICON="hom.png";this.HEMI_ICON=this.HET_ICON="het.png";this.WT_ICON="wildtype.png";this.INTERSEX_ICON="male.png";this.MIXED_ICON="wildtype.png";this.specimenMetaTemplateSource=$("#specimenMetdataTemplate").html();this.centreIcons={1:"logo_Bcm.png",3:"logo_Gmc.png",4:"logo_H.png",6:"logo_Ics.png",7:"logo_J.png",8:"logo_Tcp.png",9:"logo_Ning.png",10:"logo_Rbrc.png",11:"logo_Ucd.png",12:"logo_Wtsi.png"};this.spinner;this.spinnerOpts={lines:8,length:6,width:6,
radius:8,scale:1,corners:1,color:"#ef7b0b",opacity:.2,rotate:0,direction:1,speed:1,trail:50,fps:10,zIndex:2E9,className:"spinner",top:"20px",shadow:!1,hwaccel:!1,position:"relative"};this.monthNames="Jan Feb Mar April May June July Aug Sep Oct Nov Dec".split(" ");this.createHTML();this.updateVolumeSelector();this.jQuerySelectors();this.setupOverlayControls();this.setupRenderers();this.drawScaleBar()}};
iev.specimenview.prototype.updateData=function(a){this.volumeData=a;this.replaceVolume(this.volumeData[Object.keys(this.volumeData)[0]].volume_url);this.updateVolumeSelector()};iev.specimenview.prototype.update=function(){this.drawScaleBar();this.showMetadata()};
iev.specimenview.prototype.updateVolumeSelector=function(){$.widget("custom.iconselectmenu",$.ui.selectmenu,{_renderItem:function(a,b){var c=$("<li>",{text:b.label});b.disabled&&c.addClass("ui-state-disabled");$("<span>",{style:b.element.attr("data-style"),"class":"ui-icon "+b.element.attr("data-class")}).appendTo(c);return c.appendTo(a)}});$("#"+this.vselector).find("option").remove().end();var a=[],b;for(b in this.volumeData){var c=this.volumeData[b].volume_url,d=this.volumeData[b].sex.toLowerCase();
c===this.currentVolume.volume_url?(a.push("<option value='"+c+"' data-class='"+d+"' selected>"+this.basename(c)+"</option>"),this.bookmarkHasVolume=!1):a.push("<option value='"+c+"' data-class='"+d+"'>"+this.basename(c)+"</option>")}$("#"+this.vselector).append(a.join(""));$("#"+this.vselector).iconselectmenu().iconselectmenu("menuWidget").addClass("ui-menu-icons customicons");$("#"+this.vselector).iconselectmenu({change:$.proxy(function(a,b){this.bookmarkHasVolume||this.replaceVolume(b.item.value)},
this)}).iconselectmenu("refresh")};iev.specimenview.prototype.setupOverlayControls=function(){$("#"+this.overlayControl).buttonset();$("#"+this.overlayControl).click(function(a){a=$("input[type=radio]:checked",a.currentTarget).prop("id").split("_")[0];this.currentLabelmap!==a&&(this.currentLabelmap=a,this.replaceVolume(this.currentVolume.volume_url))}.bind(this))};
iev.specimenview.prototype.showMetadata=function(){var a=this.currentVolume.experimentDate?new Date(this.currentVolume.experimentDate):new Date(this.currentVolume.dateAnalysed),b=this.monthNames[a.getMonth()],b=b+(" "+a.getDate()),b=b+(" "+a.getFullYear()),a="female"===this.currentVolume.sex.toLowerCase()?this.IMG_DIR+this.FEMALE_ICON:"male"===this.currentVolume.sex.toLowerCase()?this.IMG_DIR+this.MALE_ICON:this.IMG_DIR+this.INTERSEX_ICON,c;if(this.currentVolume.colonyId===this.WILDTYPE_COLONYID)c=
this.WT_ICON;else switch(this.currentVolume.zygosity.toLowerCase()){case "homozygous":console.log("hello");c=this.HOM_ICON;break;case "heterozygous":console.log("hettttt");c=this.HET_ICON;break;case "hemizygous":console.log("hemiiiii");c=this.HEMI_ICON;break;default:console.log("other"),c=this.MIXED_ICON}c=this.IMG_DIR+c;var d="";this.centreIcons.hasOwnProperty(this.currentVolume.cid)&&(d=this.ICONS_DIR+this.centreIcons[this.currentVolume.cid]);b={animalId:this.currentVolume.animalName,date:b,sexIconPath:a,
zygIconPath:c,centreLogoPath:d};a=Handlebars.compile(this.specimenMetaTemplateSource);b=$(a(b));$("#metadata_"+this.id).empty();$("#metadata_"+this.id).append(b)};
iev.specimenview.prototype.setContrastSlider=function(){console.log(this.volume.min);this.$windowLevel.slider({range:!0,min:parseInt(this.volume.min),max:parseInt(this.volume.max),step:Math.ceil((this.volume.max-this.volume.min)/256),values:[parseInt(this.volume.windowLow),parseInt(this.volume.windowHigh)],slide:$.proxy(function(a,b){this.volume.windowLow=b.values[0];this.volume.windowHigh=b.values[1];this.volume.modified(!0)},this)})};
iev.specimenview.prototype.setLabelmap=function(a){"none"!==a&&(this.volume.labelmap.file=this.currentVolume[a+"_overlay"],this.volume.labelmap.colortable.file=this.currentVolume[a+"_cmap"])};iev.specimenview.prototype.showHideOverlayControls=function(){this.hasLabelmap?this.$overlayControl.show():this.$overlayControl.hide()};
iev.specimenview.prototype.setBookmarkContrast=function(){var a=parseInt(this.volume.windowLow);null!==this.contrast.lower&&(a=Math.max(this.contrast.lower,parseInt(this.volume.windowLow)));var b=parseInt(this.volume.windowHigh);null!==this.contrast.upper&&(b=Math.min(this.contrast.upper,parseInt(this.volume.windowHigh)));this.volume.windowLow=a;this.volume.windowHigh=b;this.volume.modified(!1);this.$windowLevel.slider("option","values",[this.volume.windowLow,this.volume.windowHigh])};
iev.specimenview.prototype.reset=function(){this.xRen.resetViewAndRender();this.yRen.resetViewAndRender();this.zRen.resetViewAndRender();var a=this.volume.dimensions;this.volume.indexX=Math.floor((a[0]-1)/2);this.volume.indexY=Math.floor((a[1]-1)/2);this.volume.indexZ=Math.floor((a[2]-1)/2);this.$xSlider.slider("value",this.volume.indexX);this.$ySlider.slider("value",this.volume.indexY);this.$zSlider.slider("value",this.volume.indexZ);this.$windowLevel.slider("option","values",[this.volume.windowLow,
this.volume.windowHigh]);$(".scale_outer").css({height:"100%",bottom:"30px",width:"20px",position:"relative",left:"20px","z-index":900});this.update()};
iev.specimenview.prototype.createHTML=function(){var a=$("#"+this.viewContainer);if(!(1>this.objSize(this.volumeData)&&null!==this.queryColonyId)){var b={id:this.id},c=$("#specimen_view_template").html(),c=Handlebars.compile(c),c=$(c(b));c.append(this.controls_tab());c.append(this.createSliceView("X"));c.append(this.createSliceView("Y"));c.append(this.createSliceView("Z"));var d=$("#progress_template").html(),d=Handlebars.compile(d),b=$(d(b));c.append(b);this.spinner=(new Spinner(this.spinnerOpts)).spin();
b.find(".ievLoadingMsg").append(this.spinner.el);a.append(c)}};iev.specimenview.prototype.progressStop=function(){this.spinner.stop();$("#progressMsg").empty()};iev.specimenview.prototype.createSliceView=function(a){a={sliceWrapId:"sliceWrap_"+a+"_"+this.id,sliceContainerID:a+"_"+this.id,viewSliceClasss:"slice"+a,sliderId:"slider_"+a+"_"+this.id,sliderClass:"slider"+a,orientation:a,id:this.id,scaleId:"scale_"+a+this.id,scaleTextId:"scaletext_"+a+this.id};var b=$("#slice_view_template").html();return Handlebars.compile(b)(a)};
iev.specimenview.prototype.jQuerySelectors=function(){this.$xContainer=$("#X_"+this.id);this.$yContainer=$("#Y_"+this.id);this.$zContainer=$("#Z_"+this.id);this.$xSlider=$("#slider_X_"+this.id);this.$ySlider=$("#slider_Y_"+this.id);this.$zSlider=$("#slider_Z_"+this.id);this.$xWrap=$("#sliceWrap_X_"+this.id);this.$yWrap=$("#sliceWrap_Y_"+this.id);this.$zWrap=$("#sliceWrap_Z_"+this.id);this.$windowLevel=$("#"+this.windowLevel);this.$overlayControl=$("#"+this.overlayControl)};
iev.specimenview.prototype.controls_tab=function(){var a={id:this.id,controlsButtonsId:"controlsButtons_"+this.id,selectorWrapId:"selectorWrap_"+this.id,vselectorId:this.vselector,windowLevelId:this.windowLevel,overlayId:this.overlayControl},b=$("#slice_controls_template").html();return Handlebars.compile(b)(a)};iev.specimenview.prototype.zoomIn=function(){this.xRen.camera.zoomIn(!1);this.yRen.camera.zoomIn(!1);this.zRen.camera.zoomIn(!1);this.drawScaleBar()};
iev.specimenview.prototype.zoomOut=function(){if(1>this.xRen.normalizedScale||1>this.yRen.normalizedScale||1>this.zRen.normalizedScale)return!1;this.xRen.camera.zoomOut(!1);this.yRen.camera.zoomOut(!1);this.zRen.camera.zoomOut(!1);this.drawScaleBar();return!0};
iev.specimenview.prototype.drawScaleBar=function(){setTimeout(function(){this.drawScale(this.yRen,"scale_Y"+this.id,"scaletext_Y"+this.id);this.drawScale(this.zRen,"scale_Z"+this.id,"scaletext_Z"+this.id);this.drawScale(this.xRen,"scale_X"+this.id,"scaletext_X"+this.id)}.bind(this),20)};
iev.specimenview.prototype.drawScale=function(a,b,c){var d=$(".scale_outer_"+this.id);null===this.currentVolume.rescaledPixelsize||0===this.currentVolume.rescaledPixelsize?d.hide():(d.show(),a=this.scaleBarSize/this.currentVolume.rescaledPixelsize*a.normalizedScale,d=($(".scale_outer").height()-a)/2,$("#"+b).css({height:a,width:"2px",position:"absolute",top:d}),$("#"+c).css({position:"absolute",top:d-20,"font-size":"10px"}))};iev.specimenview.prototype.rescale=function(a){this.scaleBarSize=a;this.drawScaleBar()};
iev.specimenview.prototype.getVolume=function(){return this.volume};
iev.specimenview.prototype.replaceVolume=function(a){var b={id:this.id},c=$("#"+this.id),d=$("#progress_template").html(),d=Handlebars.compile(d),b=$(d(b));c.append(b);this.spinner=(new Spinner(this.spinnerOpts)).spin();b.find(".ievLoadingMsg").append(this.spinner.el);"undefined"!==typeof this.xRen&&(this.xRen.destroy(),delete this.xRen);"undefined"!==typeof this.yRen&&(this.yRen.destroy(),delete this.yRen);"undefined"!==typeof this.zRen&&(this.zRen.destroy(),delete this.zRen);"undefined"!==typeof this.volume&&
(this.volume.destroy(),delete this.volume);this.currentVolume=this.volumeData[a];this.setupRenderers()};
iev.specimenview.prototype.setupRenderers=function(){this.ready=!1;1>this.objSize(this.volumeData)||(this.xRen=new X.renderer2D,this.xRen.config.PROGRESSBAR_ENABLED=!1,this.xRen.firstRender=!0,this.xRen.afterRender=function(){this.xRen.firstRender&&(this.xRen.resetViewAndRender(),this.xRen.firstRender=!1,this.xtk_showtime())}.bind(this),this.hasLabelmap="jacobian_overlay"in this.currentVolume,this.xRen.onShowtime=function(){this.setContrastSlider();this.showHideOverlayControls();this.setReady()}.bind(this),
this.xRen.container=this.$xContainer.get(0),this.xRen.orientation="X",this.xRen.init(),this.overrideRightMouse(this.xRen),this.yRen=new X.renderer2D,this.yRen.config.PROGRESSBAR_ENABLED=!1,this.yRen.container=this.$yContainer.get(0),this.yRen.orientation="Y",this.yRen.init(),this.overrideRightMouse(this.yRen),this.zRen=new X.renderer2D,this.zRen.config.PROGRESSBAR_ENABLED=!1,this.zRen.container=this.$zContainer.get(0),this.zRen.orientation="Z",this.zRen.init(),this.overrideRightMouse(this.zRen),this.volume=
new X.volume,this.volume.file=this.currentVolume.volume_url,this.hasLabelmap&&this.setLabelmap(this.currentLabelmap),this.xRen.add(this.volume),this.xRen.render())};iev.specimenview.prototype.overrideRightMouse=function(a){a.interactor.onMouseDown=function(a,c,d){d&&console.log("mousy R")}};iev.specimenview.prototype.setReady=function(){$("#ievLoading"+this.id).remove();ready=!0;this.readyCB()};iev.specimenview.prototype.isReady=function(){return ready};
iev.specimenview.prototype.invertColour=function(a){this.volume&&(a?(this.volume.maxColor=[0,0,0],this.volume.minColor=[1,1,1],$("#"+this.id+"> .sliceView").css("background-color","#FFFFFF"),this.volume.indexX++,this.volume.indexY++,this.volume.indexZ++):(this.volume.maxColor=[1,1,1],this.volume.minColor=[0,0,0],$("#"+this.id+"> .sliceView").css("background-color","#000000"),this.volume.indexX--,this.volume.indexY--,this.volume.indexZ--))};
iev.specimenview.prototype.sliceChange=function(a,b,c){"X"===b?this.indexCB(a,b,c+this.xOffset):"Y"===b?this.indexCB(a,b,c+this.yOffset):"Z"===b&&this.indexCB(a,b,c+this.zOffset)};iev.specimenview.prototype.setLowPowerState=function(a){this.lowPower=a};
iev.specimenview.prototype.updateSliders=function(a){a.interactor.mousemoveEvent.shiftKey?(this.$xSlider.slider("value",this.volume.indexX),this.$ySlider.slider("value",this.volume.indexY),this.$zSlider.slider("value",this.volume.indexZ),this.sliceChange(this.id,"X",this.volume.indexX),this.sliceChange(this.id,"Y",this.volume.indexY),this.sliceChange(this.id,"Z",this.volume.indexZ)):a.interactor.leftButtonDown&&this.$windowLevel.slider("option","values",[this.volume.windowLow,this.volume.windowHigh])};
iev.specimenview.prototype.xtk_showtime=function(){this.yRen.add(this.volume);this.yRen.render();this.zRen.add(this.volume);this.zRen.render();var a=this.volume.dimensions,b=this.config.specimen.pos;this.volume.indexX=(isNaN(b.x),b.x);this.volume.indexY=(isNaN(b.y),b.y);this.volume.indexZ=(isNaN(b.z),b.z);this.$xSlider.slider({disabled:!1,range:"min",min:0,max:a[0]-1,value:this.volume.indexX,slide:function(a,b){this.volume&&!this.lowPower&&(this.volume.indexX=b.value,this.sliceChange(this.id,"X",
this.volume.indexX))}.bind(this),stop:function(a,b){this.volume&&this.lowPower&&(this.volume.indexX=b.value,sliceChange(this.id,"X",this.volume.indexX))}.bind(this)});this.$ySlider.slider({disabled:!1,range:"min",min:0,max:a[1]-1,value:this.volume.indexY,slide:function(a,b){this.volume&&!this.lowPower&&(this.volume.indexY=b.value,this.sliceChange(this.id,"Y",this.volume.indexY))}.bind(this),stop:function(a,b){this.volume&&this.lowPower&&(this.volume.indexY=b.value,this.sliceChange(this.id,"Y",this.volume.indexY))}.bind(this)});
this.$zSlider.slider({disabled:!1,range:"min",min:0,max:a[2]-1,value:this.volume.indexZ,slide:function(a,b){this.volume&&!this.lowPower&&(this.volume.indexZ=b.value,sliceChange(id,"Z",this.volume.indexZ))}.bind(this),stop:function(a,b){this.volume&&this.lowPower&&(this.volume.indexZ=b.value,sliceChange(this.id,"Z",this.volume.indexZ))}.bind(this)});this.xRen.interactor.onMouseWheel=function(a){this.$xSlider.slider({value:this.volume.indexX});this.sliceChange(id,"X",this.volume.indexX)}.bind(this);
this.yRen.interactor.onMouseWheel=function(a){this.$ySlider.slider({value:this.volume.indexY});this.sliceChange(id,"Y",this.volume.indexY)}.bind(this);this.zRen.interactor.onMouseWheel=function(a){this.$zSlider.slider({value:this.volume.indexZ});this.sliceChange(id,"Z",this.volume.indexZ)}.bind(this);this.xRen.interactor.onMouseMove=function(a){this.updateSliders(this.xRen,a)}.bind(this);this.yRen.interactor.onMouseMove=function(a){this.updateSliders(this.yRen,a)}.bind(this);this.zRen.interactor.onMouseMove=
function(a){this.updateSliders(this.zRen,a)}.bind(this);this.yRen.interactor.rightButtonDown=function(){};this.setBookmarkContrast();this.update()};iev.specimenview.prototype.setXindex=function(a){this.volume.indexX=a-this.xOffset;this.$xSlider.slider("value",this.volume.indexX)};iev.specimenview.prototype.setYindex=function(a){this.volume.indexY=a-this.yOffset;this.$ySlider.slider("value",this.volume.indexY)};
iev.specimenview.prototype.setZindex=function(a){this.volume.indexZ=a-this.zOffset;this.$zSlider.slider("value",this.volume.indexZ)};iev.specimenview.prototype.getBrightnessLower=function(){return this.volume.windowLow};iev.specimenview.prototype.getBrightnessUpper=function(){return this.volume.windowHigh};iev.specimenview.prototype.getIndex=function(a){if("X"===a)return this.volume.indexX;if("Y"===a)return this.volume.indexY;if("Z"===a)return this.volume.indexZ};
iev.specimenview.prototype.setIdxOffset=function(a,b){"X"===a&&(this.xOffset=b);"Y"===a&&(this.yOffset=b);"Z"===a&&(this.zOffset=b)};iev.specimenview.prototype.getDimensions=function(){return this.volume.dimensions};iev.specimenview.prototype.getCurrentVolume=function(){return this.currentVolume};
iev.specimenview.prototype.setVisibleViews=function(a,b,c){b=c?100:String(100/b);a.X.visible?(this.$xWrap.show(),this.$xWrap.width(b+"%")):this.$xWrap.hide();a.Y.visible?(this.$yWrap.show(),this.$yWrap.width(b+"%")):this.$yWrap.hide();a.Z.visible?(this.$zWrap.show(),this.$zWrap.width(b+"%")):this.$zWrap.hide()};iev.specimenview.prototype.basename=function(a){return a.split(/[\\/]/).pop()};iev.specimenview.prototype.objSize=function(a){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b};